Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 162

Style/Lambda:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
