language: ruby
rvm:
  - 2.2.2
  - 2.5.0
  - 2.6.1

gemfile:
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile
  - gemfiles/5.2.gemfile
  - gemfiles/6.0.gemfile

script:
  - bundle exec rspec
  - bundle exec rubocop

before_install: gem install bundler

services:
  - postgresql

addons:
  postgresql: "9.4"
